# Generated by Django 4.2.2 on 2024-02-24 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='owner',
            field=models.ForeignKey(default='default_value_here', on_delete=django.db.models.deletion.CASCADE, related_name='reply_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='replied',
            field=models.TextField(max_length=30),
        ),
    ]
