# Generated by Django 4.2.2 on 2024-02-24 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0002_alter_reply_owner_alter_reply_replied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
